# Generated by Django 4.2.5 on 2023-09-20 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='created_at',
            new_name='created',
        ),
    ]
